# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/anomaly_detection',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/anomaly_detection',
                'lib_path': 'anomaly_detection'},
  'syms': {'anomaly_detection.core': {'anomaly_detection.core.foo': ('core.html#foo', 'anomaly_detection/core.py')}}}
